# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"

  default_tags {
    tags = {
      Environment = "production"
      Region      = "us-east-1"
      Component   = "general-networking"
      ManagedBy   = "Terragrunt"
      Terraform   = "true"
    }
  }
}
