---
# This would be deployed to sync AWS Secrets Manager → Kubernetes
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aurora-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: aurora-credentials
    creationPolicy: Owner
  data:
  - secretKey: host
    remoteRef:
      key: production/aurora/app-credentials
      property: host
  - secretKey: username
    remoteRef:
      key: production/aurora/app-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: production/aurora/app-credentials
      property: password
