---
# Helm values for External Secrets Operator
# Install with: helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace -f 03-external-secrets-values.yaml

# Service Account Configuration
serviceAccount:
  create: false  # We create it separately in 02-serviceaccount.yaml
  name: external-secrets-sa

# Resource limits for production
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# High availability configuration
replicaCount: 2

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL

# Metrics and monitoring
metrics:
  service:
    enabled: true
    port: 8080
  serviceMonitor:
    enabled: true
    interval: 30s

# Webhook configuration
webhook:
  create: true
  port: 9443
  hostNetwork: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL

# Cert controller for webhook certificates
certController:
  create: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL

# Enable concurrent reconciliation
concurrent: 1

# Log level
logLevel: info

# Enable leader election for HA
leaderElect: true
