---
# ExternalSecret for application configuration secrets
# Use this for API keys, JWT secrets, etc.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-config-secrets
  namespace: app
  labels:
    app.kubernetes.io/name: external-secret
    app.kubernetes.io/component: app-config
    environment: production
  annotations:
    description: "Application configuration secrets from AWS Secrets Manager"
spec:
  refreshInterval: 5m
  
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  
  target:
    name: app-config-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: app-config
          environment: production
  
  # Option 1: Extract entire secret as-is
  dataFrom:
    - extract:
        key: /production/app/config
---
# ExternalSecret with selective key extraction
# Use this when you want to cherry-pick specific keys from a secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-api-keys
  namespace: app
  labels:
    app.kubernetes.io/name: external-secret
    app.kubernetes.io/component: api-keys
    environment: production
spec:
  refreshInterval: 10m
  
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  
  target:
    name: app-api-keys
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: api-keys
          environment: production
      data:
        # Transform keys if needed
        STRIPE_API_KEY: "{{ .stripe_key }}"
        SENDGRID_API_KEY: "{{ .sendgrid_key }}"
        JWT_SECRET: "{{ .jwt_secret }}"
  
  # Option 2: Extract specific keys from secrets
  data:
    - secretKey: stripe_key
      remoteRef:
        key: /production/app/stripe
        property: api_key
    
    - secretKey: sendgrid_key
      remoteRef:
        key: /production/app/sendgrid
        property: api_key
    
    - secretKey: jwt_secret
      remoteRef:
        key: /production/app/jwt
        property: secret
---
# ExternalSecret for TLS certificates
# Useful if you store certificates in Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-tls-cert
  namespace: app
  labels:
    app.kubernetes.io/name: external-secret
    app.kubernetes.io/component: tls
    environment: production
spec:
  refreshInterval: 24h
  
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  
  target:
    name: app-tls-cert
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: tls-cert
          environment: production
      data:
        tls.crt: "{{ .certificate }}"
        tls.key: "{{ .private_key }}"
        ca.crt: "{{ .ca_certificate }}"
  
  dataFrom:
    - extract:
        key: /production/app/tls-cert
