---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    name: app
    environment: production
    managed-by: kubectl
  annotations:
    description: "Application namespace for helium project workloads"
