---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    # This annotation links the ServiceAccount to the IAM role via IRSA
    # The role ARN should be created via Terraform in your helium project
    # Format: arn:aws:iam::<account-id>:role/<environment>-external-secrets
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/production-external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: controller
