name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - staging
      - production

jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest

    env:
      # AWS credentials come from repo secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      # Non-interactive Terraform/Terragrunt setup
      TF_IN_AUTOMATION: true
      TERRAGRUNT_NON_INTERACTIVE: true
      CHECKOV_ENABLE_LOGGING: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make
          pip install --upgrade pip
          pip install checkov trivy opentofu terragrunt

      - name: Verify tools
        run: |
          echo "Checkov version: $(checkov --version)"
          echo "Trivy version: $(trivy --version)"
          echo "Terragrunt version: $(terragrunt --version)"
          echo "OpenTofu version: $(tofu version)"

      - name: Run CI pipeline
        run: make ci
