name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - staging
      - production

jobs:
  build:
    name: Run CI
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      # Optional: add anything else your Makefile depends on
      TF_IN_AUTOMATION: true
      TERRAGRUNT_NON_INTERACTIVE: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make
          pip install --upgrade pip
          pip install checkov trivy opentofu terragrunt

      - name: Run CI pipeline
        run: make ci

